name: bloc_boiler
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-394.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  dio: ^4.0.6
  retrofit: ^3.3.1
  logger: any
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  easy_localization: ^3.0.1
  rxdart: ^0.27.6
  freezed_annotation: ^2.2.0
  lottie: ^2.0.0
  image_picker: ^0.8.6
  carousel_slider: ^4.1.1
  flutter_svg: ^1.1.6
  device_info_plus: ^8.0.0
  json_serializable: ^6.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_cirlce_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/photo_camera_ic.svg
    - assets/images/settings_right_arrow_ic.svg
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
    - assets/translations/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
